---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template creates a cross-account role to allow access
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Role Details
        Parameters:
          - pServicesRoleLabel
    ParameterLabels:
      pServicesRoleLabel:
        default: Role label
      pAccountId:
        default: Account ID
      pServicesRolePermissions:
        default: Role Permissions
Outputs:
  servicesRoleAccount:
    Description: AWS Account ID
    Value: !Ref 'AWS::AccountId'
  servicesRoleName:
    Description: Managed Cloud Services role name
    Value: !Sub '${pServicesRoleLabel}-role'
  servicesRoleArn:
    Description: Managed Cloud Services role ARN
    Value: !GetAtt 'rServicesRole.Arn'
Conditions:
  cRoleNameSpecified: !Not
    - !Equals
      - ''
      - !Ref 'pServicesRoleLabel'
Mappings:
  PermissionPolicy:
    ReadOnlyAccess:
      PolicyArn: 'arn:aws:iam::aws:policy/ReadOnlyAccess'
    PowerUser:
      PolicyArn: 'arn:aws:iam::aws:policy/PowerUserAccess'
    AdministratorAccess:
      PolicyArn: 'arn:aws:iam::aws:policy/AdministratorAccess'
Parameters:
  pAccountId:
    Default: "255820308257"
    Type: String
    Description: 'Enter Account ID of source AWS Account'
  pServicesRoleLabel:
    Type: String
    Default: cloud-services
    Description: 'Enter label for IAM resources
      (default: cloud-services)'
  pServicesRolePermissions:
    Type: String
    Default: AdministratorAccess
    Description: 'Select permission policy for the services role'
    AllowedValues:
      - ReadOnlyAccess
      - PowerUserAccess
      - AdministratorAccess
Resources:
  rServicesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !If
        - cRoleNameSpecified
        - !Sub '${pServicesRoleLabel}-role'
        - !Ref 'AWS::NoValue'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join [ "", [ "arn:aws:iam::", !Ref pAccountId, ":root" ] ]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !FindInMap
          - PermissionPolicy
          - !Ref pServicesRolePermissions
          - 'PolicyArn'
