choco install adobereader -y
choco install awscli -y
choco install azure-cli -y
choco install firefox -y
choco install git -y
choco install googlechrome -y
choco install microsoft-edge -y
choco install notepadplusplus -y
choco install powershell-core -y
choco install putty -y
choco install sysinternals -y
choco install treesizefree -y
choco install vmrc -y
choco install winscp -y
